package com.propdf.corpus

import android.content.Context
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONObject
import java.io.File
import java.security.MessageDigest

/**
 * Access to the permanent regression corpus (assets/corpus, generated by tools/corpus/make_corpus.py and
 * independently verified with poppler/qpdf/pdfium; see tools/corpus/verify_corpus.py).
 *
 * The passwords below belong to PUBLIC TEST FIXTURES only.
 */
object CorpusAssets {
    const val USER_PW = "user-pass-123"
    const val OWNER_PW = "owner-pass-456"

    private val instrumentation get() = InstrumentationRegistry.getInstrumentation()

    /** The APK that carries the assets AND the TestPdfProvider (androidTest manifest -> test package). */
    val testContext: Context get() = instrumentation.context
    val targetContext: Context get() = instrumentation.targetContext

    /** Directory served by `TestPdfProvider` as content://com.propdfeditor.test.pdfs/<name> (target app cache). */
    fun providerDir(): File = File(targetContext.cacheDir, "testpdfs").apply { mkdirs() }

    fun providerUri(name: String): android.net.Uri = android.net.Uri.parse("content://com.propdfeditor.test.pdfs/$name")

    fun workDir(label: String): File =
        File(targetContext.cacheDir, "corpus_$label").apply { deleteRecursively(); mkdirs() }

    fun bytes(name: String): ByteArray = testContext.assets.open("corpus/$name").use { it.readBytes() }

    fun copyTo(dir: File, name: String, asName: String = name): File =
        File(dir, asName).also { it.writeBytes(bytes(name)) }

    fun manifestEntry(name: String): JSONObject {
        val root = JSONObject(String(bytes("MANIFEST.json"), Charsets.UTF_8))
        return root.getJSONObject("files").getJSONObject(name)
    }

    fun sha256(file: File): String =
        MessageDigest.getInstance("SHA-256").digest(file.readBytes()).joinToString("") { "%02x".format(it) }

    /** Every non-malformed, non-encrypted PDF in the corpus (name list from the manifest). */
    fun plainDocuments(): List<String> {
        val files = JSONObject(String(bytes("MANIFEST.json"), Charsets.UTF_8)).getJSONObject("files")
        return files.keys().asSequence().filter { n ->
            val e = files.getJSONObject(n); !e.optBoolean("malformed") && !e.optBoolean("encrypted")
        }.sorted().toList()
    }
}
