pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.application' version '8.2.2'
        id 'com.android.library' version '8.2.2'
        id 'org.jetbrains.kotlin.android' version '1.9.22'
        id 'org.jetbrains.kotlin.kapt' version '1.9.22'
        id 'com.google.dagger.hilt.android' version '2.51.1'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "ProPDF Editor"
include ':app'
include ':core'
include ':viewer'
include ':editor'
include ':scanner'
include ':security'
include ':ads'
include ':annotations'
include ':storage'
include ':sync'
include ':backup'
include ':ocr'
include ':share'
include ':nas'
